repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.25
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
        args: [--exit-non-zero-on-format]

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check
        args: [--fix, --error-on-warning]
        language: python
        types: [python]

  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.3
    hooks:
      - id: check-github-workflows
