[project]
name = "sample"
version = "0.1.0"
description = "A sample library"
readme = "README.md"
authors = [
    { name = "arturofonseca", email = "arturofonseca2025@u.northwestern.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.0",
    "pandas>=3.0.4",
]

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "codespell>=2.4.2",
    "pre-commit>=4.6.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "rich>=15.0.0",
    "ruff>=0.15.20",
    "ty>=0.0.55",
]

# Codespell - https://pypi.org/project/codepsell
[tool.codespell]
count = ""
quiet-level = 3

# Codespell - https://pypi.org/project/coverage
[tool.coverage]
[tool.coverage.paths]
source = ["src/sample"]
tests = ["tests"]

[tool.coverage.run]
branch = true
sigterm = true
source = ["src/sample"]

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
    "no cover: start(?s:.)*?no cover: stop",
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
]
fail_under = 80
show_missing = true
skip_empty = true

[tool.coverage.html]
directory = "reports/htmlcov"

[tool.coverage.xml]
output = "reports/coverage-results.xml"

[tool.coverage.lcov]
output = "lcov.info"

# Pytest - https://pypi.org/project/pytest
[tool.pytest]
[tool.pytest.ini_options]
addopts = "--color=yes --strict-markers"
testpaths = ["tests"]

# Ruff - https://pypi.org/project/ruff
[tool.ruff]
src = ["src/sample"]
line-length = 100
indent-width = 4
extend-include = ["*.ipynb"]
fix = true
unsafe-fixes = true
target-version = "py314"

[tool.ruff.lint]
preview = false
fixable = ["ALL"]
select = [
    "A",
    "AIR",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "DJ",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "INT",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TD",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT"
]
ignore = [
    "ANN401",
    "B024",
    "COM",
    "CPY001",
    "E501",
    "FIX002",
    "ISC001",
    "PT009",
    "PTH123",
    "TD002",
    "TD003",
]
unfixable = [
    "ERA",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "ANN001",
    "ANN201",
    "ARG",
    "EM101",
    "INP001",
    "S101",
    "SLF001",
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.lint.isort]
known-first-party = ["sample"]
lines-after-imports = 2

[tool.ruff.format]
preview = false
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

# Ty - https://pypi.org/project/ty
[tool.ty.environment]
python-version = "3.14"

[tool.ty.terminal]
error-on-warning = true

[tool.ty.rules]
division-by-zero = "error"
possibly-missing-attribute = "error"
possibly-missing-import = "error"
possibly-unresolved-reference = "error"
unused-ignore-comment = "error"
